const images = {
  transparent_square: require('../assets/images/general/transparent_square.png'),
  live: require('../assets/images/general/live.png'),
  upcoming: require('../assets/images/general/upcoming.png'),
 completed: require('../assets/images/general/completed.png'),
  leagues: {
    nba: require('../assets/images/leagues/nba.png'),
    nfl: require('../assets/images/leagues/nfl.png'),
  },
  nbaLogos: {
    atlanta_hawks: require('../assets/images/nba_logos/atlanta_hawks.svg'),
    boston_celtics: require('../assets/images/nba_logos/boston_celtics.svg'),
    brooklyn_nets: require('../assets/images/nba_logos/brooklyn_nets.svg'),
    charlotte_hornets: require('../assets/images/nba_logos/charlotte_hornets.svg'),
    chicago_bulls: require('../assets/images/nba_logos/chicago_bulls.svg'),
    cleveland_cavaliers: require('../assets/images/nba_logos/cleveland_cavaliers.svg'),
    dallas_mavericks: require('../assets/images/nba_logos/dallas_mavericks.svg'),
    denver_nuggets: require('../assets/images/nba_logos/denver_nuggets.svg'),
    detroit_pistons: require('../assets/images/nba_logos/detroit_pistons.svg'),
    golden_state_warriors: require('../assets/images/nba_logos/golden_state_warriors.svg'),
    houston_rockets: require('../assets/images/nba_logos/houston_rockets.svg'),
    indiana_pacers: require('../assets/images/nba_logos/indiana_pacers.svg'),
    la_clippers: require('../assets/images/nba_logos/la_clippers.svg'),
    los_angeles_lakers: require('../assets/images/nba_logos/los_angeles_lakers.svg'),
    memphis_grizzlies: require('../assets/images/nba_logos/memphis_grizzlies.svg'),
    miami_heat: require('../assets/images/nba_logos/miami_heat.svg'),
    milwaukee_bucks: require('../assets/images/nba_logos/milwaukee_bucks.svg'),
    minnesota_timberwolves: require('../assets/images/nba_logos/minnesota_timberwolves.svg'),
    new_orleans_pelicans: require('../assets/images/nba_logos/new_orleans_pelicans.svg'),
    new_york_knicks: require('../assets/images/nba_logos/new_york_knicks.svg'),
    oklahoma_city_thunder: require('../assets/images/nba_logos/oklahoma_city_thunder.svg'),
    orlando_magic: require('../assets/images/nba_logos/orlando_magic.svg'),
    philadelphia_76ers: require('../assets/images/nba_logos/philadelphia_76ers.svg'),
    phoenix_suns: require('../assets/images/nba_logos/phoenix_suns.svg'),
    portland_trail_blazers: require('../assets/images/nba_logos/portland_trail_blazers.svg'),
    sacramento_kings: require('../assets/images/nba_logos/sacramento_kings.svg'),
    san_antonio_spurs: require('../assets/images/nba_logos/san_antonio_spurs.svg'),
    toronto_raptors: require('../assets/images/nba_logos/toronto_raptors.svg'),
    utah_jazz: require('../assets/images/nba_logos/utah_jazz.svg'),
    washington_wizards: require('../assets/images/nba_logos/washington_wizards.svg'),
  },
nbaBanners: {
  atlanta_hawks: require('../assets/images/nba_bg/atlanta_hawks.jpg'),
  boston_celtics: require('../assets/images/nba_bg/boston_celtics.jpg'),
  brooklyn_nets: require('../assets/images/nba_bg/brooklyn_nets.jpg'),
  charlotte_hornets: require('../assets/images/nba_bg/charlotte_hornets.jpg'),
  chicago_bulls: require('../assets/images/nba_bg/chicago_bulls.jpg'),
  cleveland_cavaliers: require('../assets/images/nba_bg/cleveland_cavaliers.jpg'),
  dallas_mavericks: require('../assets/images/nba_bg/dallas_mavericks.jpg'),
  denver_nuggets: require('../assets/images/nba_bg/denver_nuggets.jpg'),
  detroit_pistons: require('../assets/images/nba_bg/detroit_pistons.jpg'),
  golden_state_warriors: require('../assets/images/nba_bg/golden_state_warriors.jpg'),
  houston_rockets: require('../assets/images/nba_bg/houston_rockets.jpg'),
  indiana_pacers: require('../assets/images/nba_bg/indiana_pacers.jpg'),
  la_clippers: require('../assets/images/nba_bg/la_clippers.jpg'),
  los_angeles_lakers: require('../assets/images/nba_bg/los_angeles_lakers.jpg'),
  memphis_grizzlies: require('../assets/images/nba_bg/memphis_grizzlies.jpg'),
  miami_heat: require('../assets/images/nba_bg/miami_heat.jpg'),
  milwaukee_bucks: require('../assets/images/nba_bg/milwaukee_bucks.jpg'),
  minnesota_timberwolves: require('../assets/images/nba_bg/minnesota_timberwolves.jpg'),
  new_orleans_pelicans: require('../assets/images/nba_bg/new_orleans_pelicans.jpg'),
  new_york_knicks: require('../assets/images/nba_bg/new_york_knicks.jpg'),
  oklahoma_city_thunder: require('../assets/images/nba_bg/oklahoma_city_thunder.jpg'),
  orlando_magic: require('../assets/images/nba_bg/orlando_magic.jpg'),
  philadelphia_76ers: require('../assets/images/nba_bg/philadelphia_76ers.jpg'),
  phoenix_suns: require('../assets/images/nba_bg/phoenix_suns.jpg'),
  portland_trail_blazers: require('../assets/images/nba_bg/portland_trail_blazers.jpg'),
  sacramento_kings: require('../assets/images/nba_bg/sacramento_kings.jpg'),
  san_antonio_spurs: require('../assets/images/nba_bg/san_antonio_spurs.jpg'),
  toronto_raptors: require('../assets/images/nba_bg/toronto_raptors.jpg'),
  utah_jazz: require('../assets/images/nba_bg/utah_jazz.jpg'),
  washington_wizards: require('../assets/images/nba_bg/washington_wizards.jpg'),
}
};

export default images;
